CREATE TABLE MSG_W01_MESSAGES (
  ID            BIGINT PRIMARY KEY,
  IDENTIFIER    VARCHAR(32)   NOT NULL
  COMMENT '消息标识',
  MSG_TIME      DATETIME      NOT NULL
  COMMENT '消息时间',
  IMEI          VARCHAR(32)   NOT NULL
  COMMENT 'IMEI',
  ENDPOINT_TYPE CHAR(1)       NOT NULL
  COMMENT 'T: Terminal; S: Server',
  INSTRUCTION   INT           NOT NULL
  COMMENT '指令',
  PARAMETERS    VARCHAR(1024) COMMENT '参数',
  PLAIN         VARCHAR(2048) NOT NULL
  COMMENT '原报文',
  STATUS        INT           NOT NULL
  COMMENT '状态:0.回复成功;-1.回复失败;-2.API指令发送失败;',
  TS            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '消息';

CREATE INDEX IX_MSG_W01_MESSAGES_IMEI_E_STATUS_T ON MSG_W01_MESSAGES (IMEI, ENDPOINT_TYPE, STATUS, TS);
